python-sip: fix compile error
Since the update of Python to version 3.11 in commit
738500c296c8b1206f20e94ca3e7c5932a6a0486 ("package/python3: bump to
version 3.11.0"), python-sip fails to compile with:

siplib.c: In function ‘sip_api_get_frame’:
siplib.c:13750:22: error: invalid use of undefined type ‘struct _frame’
13750 |         frame = frame->f_back;

This is due to a change in the Python C API, which is fixed by a new
patch. The patch can't be upstreamed, as SIP 4.x is no longer
maintained upstream.

Fixes:

  http://autobuild.buildroot.net/results/7b01739e7514e48c06182bc1804b32497ce2e414/

Signed-off-by: Ralf Dragon <hypnotoad@lindra.de>
[Thomas: improved commit log, reformatted patch using Git]
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
Issue: #SUPPORT-2066
Change-Id: Ie968b8f5182a86db287cfcd614c0813568d92849
(cherry picked from commit 3ef6884e6d59744d83649170822a4829eed146fc)