add missing SIP module for PyQt5
This fixes the following runtime error when importing PyQt5 in python:

from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5.sip'

The problem was likely triggered by the atomic upgrade from 5.7 to
5.15 in b36ce7e. This commit is part of the 2022-2024 LTS.

Signed-off-by: Ralf Dragon <hypnotoad@lindra.de>
Tested-by: Andreas Naumann <anaumann@ultratronik.de>
Signed-off-by: Julien Olivain <ju.o@free.fr>
Issue: #SUPPORT-2066
Change-Id: If68bce5c5c531149957ec4c0042aeaf645a279f4
(cherry picked from commit ba09a448f1e2e3b3123384ddddeb62d18bfa9461)